config/routes.rb
################################################################################
#
#   29.03.2018  Bug fixed for logout error (is it since Rails 5.2?):
#                 No route matches [GET] "/ru/logout" 
#               Solution: *get* instead of *delete*  - has been canceled (see below)
#               
#               Later: The bug is vanishing if to use *jquery_ujs* - MUSR BE!
################################################################################
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
     #get    'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
   #get    'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
    
    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
################################################################################
# Model:  User
#
# Purpose:
#
# User attributes:
#   role              - role:           enum
#   last_name             - string:
#   first_name             - string:
#   email             - email:          string,  not NULL, unique
#   password_digest   - password:       string, not NULL
#   remember_token    - remember token: string
#   status            - status:         enum { active (0) | archived (1) }
#
#  07.07.2016 ZT
################################################################################
class User < ApplicationRecord
  before_save {self.email.downcase!}

  enum role:   %w(manager admin sysadmin)
  enum status: %w(active archived)


  validates :last_name,  presence: true
  validates :first_name, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  has_secure_password                      # validates presence of password & password_confirmation
  validates :password, length: {minimum: 8}


  # Returns an User full name
  def full_name
    "#{last_name} #{first_name}"
  end

  private

    # Returns a random token
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    # Returns a random token.
    def User.new_token
      SecureRandom.urlsafe_base64
    end

    # Remembers a user in the database to apply him/her in persistent sessions
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    authorize @users
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def edit
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user

    if @user.save
      flash[:success] = t('messages.created', model: @user.class.model_name.human)
      redirect_to [:admin, @user]
#     redirect_to polymorphic_url([:admin, @user], locale: params[:locale]), notice: t('messages.created', model: @user.class.model_name.human)
    else
      render :new
    end
  end

  def update
    authorize @user
    if @user.update(user_params)
      flash[:success] = t('messages.updated', model: @user.class.model_name.human)
      redirect_to [:admin, @user]
#     redirect_to polymorphic_url([:admin, @user], locale: params[:locale]), notice: t('messages.updated', model: @user.class.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    @user.destroy
    flash[:success] = t('messages.deleted', model: @user.class.model_name.human)
    redirect_to admin_users_path
  end

  private

    # Uses callbacks to share common setup or constraints between actions
    def set_user
      @user = User.find(params[:id])
    end

    # Only allows a trusted parameter 'white list' through
    def user_params
      params.require(:user).permit(:role, :last_name, :first_name, :email, :password_digest, :remember_digest, :status, :password, :password_confirmation)
    end
end

app/views/admin/users/_form.html.haml
.row
  .col-md-6
    = simple_form_for([:admin, @user], html: {multipart: true}, url: (@user.id.nil? ? {action: 'create', locale: params[:locale]} : {action: 'update', locale: params[:locale]})) do |f|
      = f.error_notification  message: t('messages.error_notification')

      .form-inputs
        = f.input :role, include_blank: false
        = f.input :last_name
        = f.input :first_name
        = f.input :email
        = f.input :password
        = f.input :password_confirmation

        = f.input :status                               # DDL
        /= render 'admin/shared/status_buttons', f: f   # Radio-buttons

      .form_actions
        .row
          .col-md-3
            = f.submit t('actions.save'), class: 'btn btn-primary btn-block'
          .col-md-3
            - if @current_user.sysadmin?
              = link_to t('actions.back'), admin_users_path, class: 'btn btn-default btn-block'

app/views/admin/users/edit.html.haml
%h1= "#{t('actions.editing', model: @user.class.model_name.human)}"
= render 'form'

app/views/admin/users/index.html.haml
%h1= t User.model_name.human(count: 2)
%table.table.table-hover
  %thead
    %tr
      %th= User.human_attribute_name(:role)
      %th= User.human_attribute_name(:last_name)
      %th= User.human_attribute_name(:first_name)
      %th= User.human_attribute_name(:email)
      %th= t 'status.status'
      %th= t 'actions.actions'

  %tbody
    - @users.each do |user|
      %tr
        %td= user.role
        %td= user.last_name
        %td= user.first_name
        %td= user.email
        %td= status_mark user.status
        %td= render 'admin/shared/index_buttons', resource: user
%br
.row
  .col-md-2
    = link_to t('actions.create'), new_admin_user_path, class: 'btn btn-primary btn-block'

app/views/admin/users/new.html.haml
%h1= "#{t('actions.new', model: @user.class.model_name.human)}"
= render 'form'

app/views/admin/users/show.html.haml
%h1= t User.model_name.human
%table.table.table-striped
  %tbody
    - @user.attributes.each do |key, value|
      - if key == 'id' || key.include?('digest') || key == 'created_at' || key == 'updated_at'
        //skip these attributes
      -else
        %tr
          - if key == 'status'
            %td= t 'status.status'
            %td= status_mark @user.status
          -else
            %td= t "activerecord.attributes.user.#{key}"
            %td= value

.form_actions
  .row
    .col-md-1
      = link_to t('actions.back'), admin_users_path, class: 'btn btn-primary btn-block'