config/routes.rb
################################################################################
#
#   29.03.2018  Bug fixed for logout error (is it since Rails 5.2?):
#                 No route matches [GET] "/ru/logout" 
#               Solution: *get* instead of *delete*  - has been canceled (see below)
#               
#               Later: The bug is vanishing if to use *jquery_ujs* - MUSR BE!
################################################################################
Rails.application.routes.draw do

  if MULTILINGUAL

    scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do

      # Session resources
      get    'sessions/new'                                 # sessions_new_path
      post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
      delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
     #get    'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)

      namespace :admin do
        root 'panel#index'                                  # admin_root_path
        resources :users
        # 1: Add new admin resources before this line
      end

      root   'pages#home'                                   # root_path

    end

    # Root route is directed to default locale
    root to: redirect("/#{I18n.default_locale}", status: 302), as: :redirected_root

    # All other routes without locales are directed to the same ones with locales
    get "/*path", to: redirect("/#{I18n.default_locale}/%{path}", status: 302), constraints: {path: /(?!(#{I18n.available_locales.join("|")})\/).*/}, format: false

  else

    # Session resources
    get    'sessions/new'                                 # sessions_new_path
    post   'login',   to: 'sessions#create'               # login_path  - creates new session (login)
    delete 'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
   #get    'logout',  to: 'sessions#destroy', as: :logout # logout_path - deletes session (log out)
    
    namespace :admin do
      root 'panel#index'                                  # admin_root_path
      resources :users
      # 2: Add new admin resources before this line
    end

    root   'pages#home'                                   # root_path

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_admin_header.html.haml
/ Not used now
%h4= "#{User.model_name.human}: #{current_user.full_name}"

app/views/admin/shared/_admin_top_navigation.html.haml
/ https://www.quackit.com/bootstrap/bootstrap_4/tutorial/bootstrap_navbars.cfm

.container-fluid
  %nav.navbar.navbar-expand-sm.navbar-light.bg-faded
    / Toggle menu
    %button.navbar-toggler{"aria-controls" => "nav-content", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#nav-content", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon

    / Brand (App Home Page)
    .navbar-brand 
      = link_to image_tag('logos/dummy_logo.png', title: app_name,  size: '142x82'), root_path

    / Links
    #nav-content.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          .nav-link
            = link_to  admin_root_path do
              %span.fa.fa-home.fa-2x{"aria-hidden" => "true"}
              = t(:admin_home)
        %li.nav-item
          - if @current_user.sysadmin?
            .nav-link
              = link_to admin_users_path do
                /%span.fa.fa-home{"aria-hidden" => "true"}
                %span.fa.fa-user-circle-o.fa-2x{"aria-hidden" => "true"}
                = t User.model_name.human(count: 2)
          - else
            .nav-link
              = link_to edit_admin_user_path(@current_user) do
                %span.fa.fa-user-circle.fa-2x{"aria-hidden" => "true"}
                = t(:profile)

        / Dropdown list

        %li.nav-item.dropdown
          #Preview.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
            = link_to "#" do
              %span.fa.fa-database.fa-2x{"aria-hidden" => "true"}
              = t(:data)
          .dropdown-menu{"aria-labelledby" => "Preview"}
            .dropdown-item
              = link_to t(:dummy), '#'
              /= link_to t(Account.model_name.human(count: 2)),  admin_accounts_path
            .dropdown-item
              = link_to t(:dummy), '#'
              /= link_to (t(Product.model_name.human(count: 2)), admin_productss_path

      %ul.nav.navbar-nav
        - if MULTILINGUAL
          %li.nav-item.dropdown
            #Preview.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :role => "button"}
              = link_to "#" do
                %span.fa.fa-language.fa-2x{"aria-hidden" => "true"}
                = t(:language)
            = language_switch_bootstrap('admin')
        %li.nav-item
          .nav-link
            = link_to(logout_path, method: 'delete') do
              %span.fa.fa-sign-out.fa-2x{"aria-hidden" => "true"}
              = t 'simple_form.submit.logout'

app/views/admin/shared/_admin_top_navigation_old.html.haml
/ source: http://www.w3schools.com/bootstrap/bootstrap_navbar.asp

%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      / Brand and toggle get grouped for better mobile display
      %button.navbar-toggle{"data-target" => ".collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand
        = link_to app_name, admin_root_path
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to admin_root_path do
            %span.glyphicon.glyphicon-home
            = t(:admin_home)
        %li
          - if @current_user.sysadmin?
            = link_to admin_users_path do
              %span.glyphicon.glyphicon-user
              = t(:admin_users)
          - else
            = link_to edit_admin_user_path(@current_user) do
              %span.glyphicon.glyphicon-user
              = t(:profile)

        %li.dropdown
          = link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do
            %span.glyphicon.glyphicon-th-list
            = t :dummy
            %span.caret
          %ul.dropdown-menu
            %li= link_to t(:dummy),  '#'
            %li= link_to t(:dummy),  '#'
            %li= link_to t(:dummy),  '#'
            %li= link_to t(:dummy),  '#'
      %ul.nav.navbar-nav.navbar-right
        - if MULTILINGUAL
          %li.dropdown
            = link_to '#', data: {toggle: "dropdown"}, class: "dropdown-toggle" do
              = t :language
              %span.caret
            = language_switch_bootstrap('admin')
        %li
          = link_to(logout_path, method: 'delete') do
            %span.glyphicon.glyphicon-log-out
            = t 'simple_form.submit.logout'

app/views/admin/shared/_index_buttons.html.haml
= link_to t('actions.show'),   [:admin, resource],        class: 'btn btn-primary btn-sm'
= link_to t('actions.edit'),   [:edit, :admin, resource], class: 'btn btn-warning btn-sm'
= link_to t('actions.delete'), [:admin, resource],        class: 'btn btn-danger  btn-sm', method: :delete, data: {confirm: t('messages.confirm')}


/ ref: https://makandracards.com/makandra/1375-url_for-with-added-params not needed if *default_url_options* method is applied

/= link_to t('actions.show'),   polymorphic_url([:admin, resource],        locale: params[:locale]), class: 'btn btn-primary btn-xs'
/= link_to t('actions.edit'),   polymorphic_url([:edit, :admin, resource], locale: params[:locale]), class: 'btn btn-warning btn-xs'
/= link_to t('actions.delete'), polymorphic_url([:admin, resource],        locale: params[:locale]), class: 'btn btn-danger  btn-xs', method: :delete, data: {confirm: t('messages.confirm')}

app/views/admin/shared/_status_buttons.html.haml
%p.p-status
  = "#{t('status.status')}:"
  &nbsp;&nbsp;
  = f.radio_button :status, :active, checked: true
  = label :status, t('status.active')
  &nbsp;
  = f.radio_button :status, :archived
  = label :status, t('status.archived')